#
# Copyright (C) 2021 1nfsr 
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=Knowhere
LUCI_DEPENDS:=
PKG_VERSION:=alpha
PKG_RELEASE:=20210215

PKG_LICENSE:=Apache-2.0

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature